# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\git\iperf_gui\iperf_client.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 729)
        MainWindow.setMinimumSize(QtCore.QSize(590, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.pushButton_a = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_a.setFont(font)
        self.pushButton_a.setObjectName("pushButton_a")
        self.horizontalLayout_14.addWidget(self.pushButton_a)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.pushButton_s = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_s.setFont(font)
        self.pushButton_s.setObjectName("pushButton_s")
        self.horizontalLayout_14.addWidget(self.pushButton_s)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_iperf3 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_iperf3.setObjectName("widget_iperf3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_iperf3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_32 = QtWidgets.QLabel(self.widget_iperf3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_33.addWidget(self.label_32)
        self.label_res_rx = QtWidgets.QLabel(self.widget_iperf3)
        self.label_res_rx.setMinimumSize(QtCore.QSize(105, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_res_rx.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_res_rx.setFont(font)
        self.label_res_rx.setText("")
        self.label_res_rx.setObjectName("label_res_rx")
        self.horizontalLayout_33.addWidget(self.label_res_rx)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_34 = QtWidgets.QLabel(self.widget_iperf3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_34.addWidget(self.label_34)
        self.label_res_tx = QtWidgets.QLabel(self.widget_iperf3)
        self.label_res_tx.setMinimumSize(QtCore.QSize(105, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_res_tx.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_res_tx.setFont(font)
        self.label_res_tx.setText("")
        self.label_res_tx.setObjectName("label_res_tx")
        self.horizontalLayout_34.addWidget(self.label_res_tx)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_34)
        self.gridLayout_5.addLayout(self.horizontalLayout_15, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget_iperf3)
        self.widget_iperf2 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_iperf2.setObjectName("widget_iperf2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_iperf2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem4, 0, 1, 1, 1)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_31 = QtWidgets.QLabel(self.widget_iperf2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_32.addWidget(self.label_31)
        self.label_res_th = QtWidgets.QLabel(self.widget_iperf2)
        self.label_res_th.setMinimumSize(QtCore.QSize(105, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_res_th.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_res_th.setFont(font)
        self.label_res_th.setText("")
        self.label_res_th.setObjectName("label_res_th")
        self.horizontalLayout_32.addWidget(self.label_res_th)
        self.gridLayout_9.addLayout(self.horizontalLayout_32, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_iperf2)
        self.horizontalLayout_31.addLayout(self.verticalLayout)
        self.label_countDown = QtWidgets.QLabel(self.groupBox_4)
        self.label_countDown.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_countDown.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_countDown.setFont(font)
        self.label_countDown.setAlignment(QtCore.Qt.AlignCenter)
        self.label_countDown.setObjectName("label_countDown")
        self.horizontalLayout_31.addWidget(self.label_countDown)
        self.gridLayout_10.addLayout(self.horizontalLayout_31, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.label_error = QtWidgets.QLabel(self.tab)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_error.setPalette(palette)
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.verticalLayout_2.addWidget(self.label_error)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_test = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_test.setObjectName("groupBox_test")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_test)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_cc = QtWidgets.QCheckBox(self.groupBox_test)
        self.checkBox_cc.setText("")
        self.checkBox_cc.setObjectName("checkBox_cc")
        self.horizontalLayout_9.addWidget(self.checkBox_cc)
        self.label_7 = QtWidgets.QLabel(self.groupBox_test)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.spinBox_cCount = QtWidgets.QSpinBox(self.groupBox_test)
        self.spinBox_cCount.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_cCount.setFont(font)
        self.spinBox_cCount.setMinimum(0)
        self.spinBox_cCount.setMaximum(9999)
        self.spinBox_cCount.setObjectName("spinBox_cCount")
        self.horizontalLayout_9.addWidget(self.spinBox_cCount)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_9)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_test)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.spinBox_cInterval = QtWidgets.QSpinBox(self.groupBox_test)
        self.spinBox_cInterval.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_cInterval.setFont(font)
        self.spinBox_cInterval.setObjectName("spinBox_cInterval")
        self.horizontalLayout_10.addWidget(self.spinBox_cInterval)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_10)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.gridLayout_4.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBox_save = QtWidgets.QCheckBox(self.groupBox_test)
        self.checkBox_save.setText("")
        self.checkBox_save.setObjectName("checkBox_save")
        self.horizontalLayout_11.addWidget(self.checkBox_save)
        self.label_12 = QtWidgets.QLabel(self.groupBox_test)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.label_path = QtWidgets.QLabel(self.groupBox_test)
        self.label_path.setMinimumSize(QtCore.QSize(100, 0))
        self.label_path.setText("")
        self.label_path.setObjectName("label_path")
        self.horizontalLayout_11.addWidget(self.label_path)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_test)
        self.pushButton_save.setEnabled(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_11.addWidget(self.pushButton_save)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_test)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.checkBox_script = QtWidgets.QCheckBox(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_script.setFont(font)
        self.checkBox_script.setObjectName("checkBox_script")
        self.horizontalLayout_19.addWidget(self.checkBox_script)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem8)
        self.pushButton_refresh = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout_19.addWidget(self.pushButton_refresh)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.verticalLayout_5.addLayout(self.verticalLayout_8)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 105))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 105))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 633, 117))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_script_add = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_script_add.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_script_add.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_script_add.setObjectName("pushButton_script_add")
        self.verticalLayout_7.addWidget(self.pushButton_script_add)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.label_index = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_index.setAlignment(QtCore.Qt.AlignCenter)
        self.label_index.setObjectName("label_index")
        self.verticalLayout_7.addWidget(self.label_index)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.horizontalLayout_20.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.comboBox_script_pro = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_script_pro.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_script_pro.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_script_pro.setFont(font)
        self.comboBox_script_pro.setObjectName("comboBox_script_pro")
        self.comboBox_script_pro.addItem("")
        self.comboBox_script_pro.addItem("")
        self.comboBox_script_pro.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_script_pro)
        self.label_pro_ip = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_pro_ip.setFont(font)
        self.label_pro_ip.setObjectName("label_pro_ip")
        self.horizontalLayout_12.addWidget(self.label_pro_ip)
        self.lineEdit_script_ip = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_script_ip.setMinimumSize(QtCore.QSize(135, 0))
        self.lineEdit_script_ip.setMaximumSize(QtCore.QSize(135, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_script_ip.setFont(font)
        self.lineEdit_script_ip.setText("")
        self.lineEdit_script_ip.setObjectName("lineEdit_script_ip")
        self.horizontalLayout_12.addWidget(self.lineEdit_script_ip)
        self.comboBox_serial = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_serial.setMinimumSize(QtCore.QSize(90, 0))
        self.comboBox_serial.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_serial.setFont(font)
        self.comboBox_serial.setObjectName("comboBox_serial")
        self.horizontalLayout_12.addWidget(self.comboBox_serial)
        self.pushButton_script_more = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_script_more.setMinimumSize(QtCore.QSize(25, 0))
        self.pushButton_script_more.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_script_more.setObjectName("pushButton_script_more")
        self.horizontalLayout_12.addWidget(self.pushButton_script_more)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.comboBox_opp = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_opp.setMinimumSize(QtCore.QSize(75, 0))
        self.comboBox_opp.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_opp.setFont(font)
        self.comboBox_opp.setObjectName("comboBox_opp")
        self.comboBox_opp.addItem("")
        self.comboBox_opp.addItem("")
        self.comboBox_opp.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_opp)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_18.addWidget(self.label_17)
        self.lineEdit_script = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_script.setObjectName("lineEdit_script")
        self.horizontalLayout_18.addWidget(self.lineEdit_script)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.lineEdit_re = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_re.setObjectName("lineEdit_re")
        self.horizontalLayout_17.addWidget(self.lineEdit_re)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_20.addLayout(self.verticalLayout_6)
        self.gridLayout_12.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.label_error_t = QtWidgets.QLabel(self.tab_5)
        self.label_error_t.setText("")
        self.label_error_t.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_t.setObjectName("label_error_t")
        self.verticalLayout_5.addWidget(self.label_error_t)
        self.gridLayout_13.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 352, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem12, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_ver = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_ver.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox_ver.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.comboBox_ver.setFont(font)
        self.comboBox_ver.setObjectName("comboBox_ver")
        self.comboBox_ver.addItem("")
        self.comboBox_ver.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_ver)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.comboBox_pro = QtWidgets.QComboBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_pro.setFont(font)
        self.comboBox_pro.setObjectName("comboBox_pro")
        self.comboBox_pro.addItem("")
        self.comboBox_pro.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_pro)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_c_param = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_c_param.setFont(font)
        self.lineEdit_c_param.setObjectName("lineEdit_c_param")
        self.horizontalLayout_8.addWidget(self.lineEdit_c_param)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.lineEdit_c_ip = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_c_ip.setFont(font)
        self.lineEdit_c_ip.setObjectName("lineEdit_c_ip")
        self.horizontalLayout_3.addWidget(self.lineEdit_c_ip)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_time = QtWidgets.QSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_time.setFont(font)
        self.spinBox_time.setMaximum(999999)
        self.spinBox_time.setObjectName("spinBox_time")
        self.horizontalLayout_3.addWidget(self.spinBox_time)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox_p = QtWidgets.QSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.spinBox_p.setFont(font)
        self.spinBox_p.setObjectName("spinBox_p")
        self.horizontalLayout_3.addWidget(self.spinBox_p)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem16)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.label_error_c = QtWidgets.QLabel(self.tab_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_error_c.setPalette(palette)
        self.label_error_c.setText("")
        self.label_error_c.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_c.setObjectName("label_error_c")
        self.verticalLayout_4.addWidget(self.label_error_c)
        self.gridLayout_8.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem17, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox_3.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_3)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem18)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_4)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_s_ip = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_s_ip.setFont(font)
        self.lineEdit_s_ip.setObjectName("lineEdit_s_ip")
        self.horizontalLayout.addWidget(self.lineEdit_s_ip)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem20)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_s_param = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_s_param.setFont(font)
        self.lineEdit_s_param.setObjectName("lineEdit_s_param")
        self.horizontalLayout_5.addWidget(self.lineEdit_s_param)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.label_error_s = QtWidgets.QLabel(self.tab_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_error_s.setPalette(palette)
        self.label_error_s.setText("")
        self.label_error_s.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error_s.setObjectName("label_error_s")
        self.verticalLayout_3.addWidget(self.label_error_s)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem21, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.label_res_path = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_res_path.setFont(font)
        self.label_res_path.setText("")
        self.label_res_path.setObjectName("label_res_path")
        self.horizontalLayout_16.addWidget(self.label_res_path)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem22)
        self.gridLayout_16.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableWidget_ver2 = QtWidgets.QTableWidget(self.page)
        self.tableWidget_ver2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_ver2.setObjectName("tableWidget_ver2")
        self.tableWidget_ver2.setColumnCount(10)
        self.tableWidget_ver2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver2.setHorizontalHeaderItem(9, item)
        self.gridLayout_11.addWidget(self.tableWidget_ver2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tableWidget_ver3 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_ver3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_ver3.setObjectName("tableWidget_ver3")
        self.tableWidget_ver3.setColumnCount(8)
        self.tableWidget_ver3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ver3.setHorizontalHeaderItem(7, item)
        self.gridLayout_15.addWidget(self.tableWidget_ver3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_16.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.textBrowser_help = QtWidgets.QTextBrowser(self.tab_6)
        self.textBrowser_help.setObjectName("textBrowser_help")
        self.gridLayout_14.addWidget(self.textBrowser_help, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Iperf Client"))
        self.pushButton_a.setText(_translate("MainWindow", "START"))
        self.pushButton_s.setText(_translate("MainWindow", "STOP"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Test Result"))
        self.label_32.setText(_translate("MainWindow", "Rx:"))
        self.label_34.setText(_translate("MainWindow", "Tx:"))
        self.label_31.setText(_translate("MainWindow", "Throughput:"))
        self.label_countDown.setText(_translate("MainWindow", "360000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Testing"))
        self.groupBox_test.setTitle(_translate("MainWindow", "Test Setting"))
        self.label_7.setText(_translate("MainWindow", "循环次数:"))
        self.label_11.setText(_translate("MainWindow", "循环间隔/s："))
        self.label_12.setText(_translate("MainWindow", "数据自动保存路径："))
        self.pushButton_save.setText(_translate("MainWindow", "浏览"))
        self.checkBox_script.setText(_translate("MainWindow", "Script"))
        self.pushButton_refresh.setText(_translate("MainWindow", "Rfresh"))
        self.pushButton_script_add.setText(_translate("MainWindow", "+"))
        self.label_index.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "Protocol:"))
        self.comboBox_script_pro.setItemText(0, _translate("MainWindow", "SSH2"))
        self.comboBox_script_pro.setItemText(1, _translate("MainWindow", "TELNET"))
        self.comboBox_script_pro.setItemText(2, _translate("MainWindow", "SERIAL"))
        self.label_pro_ip.setText(_translate("MainWindow", "IP:"))
        self.pushButton_script_more.setText(_translate("MainWindow", "..."))
        self.label_13.setText(_translate("MainWindow", "运行:"))
        self.comboBox_opp.setItemText(0, _translate("MainWindow", "测试后"))
        self.comboBox_opp.setItemText(1, _translate("MainWindow", "测试中"))
        self.comboBox_opp.setItemText(2, _translate("MainWindow", "测试前"))
        self.label_17.setText(_translate("MainWindow", "运行脚本:"))
        self.label_18.setText(_translate("MainWindow", "结果匹配:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Test Setting"))
        self.label_2.setText(_translate("MainWindow", "iperf version:"))
        self.comboBox_ver.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox_ver.setItemText(1, _translate("MainWindow", "3"))
        self.label_9.setText(_translate("MainWindow", "测试协议:"))
        self.comboBox_pro.setItemText(0, _translate("MainWindow", "TCP"))
        self.comboBox_pro.setItemText(1, _translate("MainWindow", "UDP"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Client端设置"))
        self.label_8.setText(_translate("MainWindow", "参数:"))
        self.lineEdit_c_param.setText(_translate("MainWindow", "-l 1024 -i 1"))
        self.label_14.setText(_translate("MainWindow", "IP:"))
        self.lineEdit_c_ip.setText(_translate("MainWindow", "192.168.10.210"))
        self.label_3.setText(_translate("MainWindow", "Time:"))
        self.label_4.setText(_translate("MainWindow", "线程数:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Client Setting"))
        self.label_6.setText(_translate("MainWindow", "iperf version:"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "3"))
        self.label_10.setText(_translate("MainWindow", "测试协议:"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "TCP"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "UDP"))
        self.groupBox.setTitle(_translate("MainWindow", "Server端设置"))
        self.label.setText(_translate("MainWindow", "Server 端 IP："))
        self.lineEdit_s_ip.setText(_translate("MainWindow", "255.255.255.255"))
        self.label_5.setText(_translate("MainWindow", "参数:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Server Setting"))
        self.label_15.setText(_translate("MainWindow", "Excel:"))
        item = self.tableWidget_ver2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Protocol"))
        item = self.tableWidget_ver2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Throughput/Mbps"))
        item = self.tableWidget_ver2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Loss"))
        item = self.tableWidget_ver2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Delay/ms"))
        item = self.tableWidget_ver2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Throughput/Mbps"))
        item = self.tableWidget_ver2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Loss"))
        item = self.tableWidget_ver2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Delay/ms"))
        item = self.tableWidget_ver2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Up/Down"))
        item = self.tableWidget_ver2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_ver2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "备注"))
        item = self.tableWidget_ver3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Protocol"))
        item = self.tableWidget_ver3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tx/Mbps"))
        item = self.tableWidget_ver3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rx/Mpbs"))
        item = self.tableWidget_ver3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Loss"))
        item = self.tableWidget_ver3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Delay/ms"))
        item = self.tableWidget_ver3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Up/Down"))
        item = self.tableWidget_ver3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_ver3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "备注"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Result"))
        self.textBrowser_help.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">iperf v2:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  <span style=\" font-size:11pt;\">-s 以server模式启动，eg：iperf -s </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -c host以client模式启动，host是server端地址，</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    eg：iperf -  c 222.35.11.23 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\"> </span><span style=\" font-size:11pt; font-weight:600;\"> 通用参数 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -f [kmKM] 分别表示以Kbits, Mbits, KBytes, MBytes显示报告，</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    默认以Mbits为单位,eg：iperf -c 222.35.11.23 -f K </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -i sec 以秒为单位显示报告间隔，eg：iperf -c 222.35.11.23 -i 2 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -l 缓冲区大小，默认是8KB,eg：iperf -c 222.35.11.23 -l 16 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -m 显示tcp最大mtu值 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -o 将报告和错误信息输出到文件</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    eg：iperf -c 222.35.11.23 -o ciperflog.txt </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -p 指定服务器端使用的端口或客户端所连接的端口</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    eg： iperf -s -p 9999;iperf -c 222.35.11.23 -p 9999 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -u 使用udp协议 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -w 指定TCP窗口大小，默认是8KB </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -B 绑定一个主机地址或接口（当主机有多个地址或接口时使用该参数） </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -C 兼容旧版本（当server端和client端版本不一样时使用） </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -M 设定TCP数据包的最大mtu值 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -N 设定TCP不延时 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -V 传输ipv6数据包 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  </span><span style=\" font-size:11pt; font-weight:600;\">server专用参数 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -D 以服务方式运行iperf，eg：iperf -s -D </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -R 停止iperf服务，针对-D，eg：iperf -s -R </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  </span><span style=\" font-size:11pt; font-weight:600;\">client端专用参数</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -d 同时进行双向传输测试 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -n 指定传输的字节数，eg：iperf -c 222.35.11.23 -n 100000 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -r 单独进行双向传输测试 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -t 测试时间，默认10秒,eg：iperf -c 222.35.11.23 -t 5 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -F 指定需要传输的文件 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">  -T 指定ttl值 </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">iperf v3</span>:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -p, --port #，Server 端监听、Client 端连接的端口号；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -f, --format [kmgKMG]，报告中所用的数据单位:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    Kbits, Mbits, KBytes, Mbytes；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -i, --interval #，每次报告的间隔，单位为秒；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -F, --file name，测试所用文件的文件名。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    如果使用在 Client 端，发送该文件用作测试；</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    如果使用在 Server 端，则是将数据写入该文件，而不是丢弃；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -A, --affinity n/n,m，设置 CPU 亲和力；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -B, --bind ，绑定指定的网卡接口；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -V, --verbose，运行时输出更多细节；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -J, --json，运行时以 JSON 格式输出结果；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  --logfile f，输出到文件；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -d, --debug，以 debug 模式输出结果；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -v, --version，显示版本信息并退出；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -h, --help，显示帮助信息并退出。</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt; font-weight:600;\">  Server 端参数</span><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">：</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -s, --server，以 Server 模式运行；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -D, --daemon，在后台以守护进程运行；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -I, --pidfile file，指定 pid 文件；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -1, --one-off，只接受 1 次来自 Client 端的测试，然后退出。</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt; font-weight:600;\">  Client 端参数</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -c, --client ，以 Client 模式运行，并指定 Server 端的地址；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -u, --udp，以 UDP 协议进行测试；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -b, --bandwidth #[KMG][/#]，限制测试带宽。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    UDP 默认为 1Mbit/秒，TCP 默认无限制；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -t, --time #，以时间为测试结束条件进行测试，默认为 10 秒；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -n, --bytes #[KMG]，以数据传输大小为测试结束条件进行测试；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -k, --blockcount #[KMG]，</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    以传输数据包数量为测试结束条件进行测试；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -l, --len #[KMG]，读写缓冲区的长度，</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    TCP 默认为 128K，</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    UDP 默认为 8K；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  --cport ，指定 Client 端运行所使用的 TCP 或 UDP 端口，</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    默认为临时端口；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -P, --parallel #，测试数据流并发数量；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -R, --reverse，反向模式运行（Server 端发送，Client 端接收）；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -w, --window #[KMG]，设置套接字缓冲区大小，</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    TCP 模式下为窗口大小；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -C, --congestion ，设置 TCP 拥塞控制算法</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    （仅支持 Linux 和 FreeBSD ）；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -M, --set-mss #，设置 TCP/SCTP 最大分段长度</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    （MSS，MTU 减 40 字节）；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -N, --no-delay，设置 TCP/SCTP no delay，屏蔽 Nagle 算法；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -4, --version4，仅使用 IPv4；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -6, --version6，仅使用 IPv6；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -S, --tos N，设置 IP 服务类型（TOS，Type Of Service）；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -L, --flowlabel N，设置 IPv6 流标签（仅支持 Linux）；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -Z, --zerocopy，使用 “zero copy”（零拷贝）方法发送数据；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -O, --omit N，忽略前 n 秒的测试；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  -T, --title str，设置每行测试结果的前缀；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  --get-server-output，从 Server 端获取测试结果；</span> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">  --udp-counters-64bit，在 UDP 测试包中使用 64 位计数器</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei\'; font-size:11pt;\">    （防止计数器溢出）。</span> </p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
